### ISSUE TITLE
O projeto não está estruturado

### ISSUE THREAD

**Issue by larguesa** [BryanCSAL/Robata#1]
Há alguns arquivos hospedado neste repositório, mas não o projeto em si. É preciso manter o projeto estruturado aqui. Neste vídeo, explico como usar o GitHub Desktop para compartilhar um projeto em um repositório do GitHub:
https://youtu.be/zRedD7LTahs?si=cezvi2iYM91wcRzE

**Comment by AntonioUrata** [comment]
Professor, vimos o vídeo e já atualizamos o que foi pedido. Se houver mais algo para ser corrigido, nos fale por favor, porém ainda estamos em processo de desenvolvimento... Agradecemos desde já.
